[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "dynamic-anomaly-detection-api"
version = "0.1.0"
description = "Dynamic anomaly detection using API data"
requires-python = ">=3.9"

[tool.setuptools.packages.find]
where = ["."]
